STRING(COMPARE EQUAL ${CMAKE_SYSTEM_NAME} "Windows" NTS_COMPILE_ON_WINDOWS)
STRING(COMPARE EQUAL ${CMAKE_SYSTEM_NAME} "Linux" NTS_COMPILE_ON_LINUX)

if(NTS_COMPILE_ON_WINDOWS)
	set(WINDOWS ON)		
endif()

if(NTS_COMPILE_ON_LINUX)
	set(LINUX ON)		
endif()